CREATE OR REPLACE VIEW ClienteView AS
SELECT CODIGO_INTERNO AS "Client ID", NOME AS "Name",CASE
  WHEN VALOR_ENCOMENDAS_ANUAL >= 10000 THEN 'A'
  WHEN VALOR_ENCOMENDAS_ANUAL >= 5000 THEN 'B'
  ELSE 'C'
  END as "LEVEL",
  COALESCE(TO_CHAR(DATA_INCIDENTE), 'No incidents to date') AS "Last Incident",
  (SELECT count(*) FROM ENCOMENDA E
  WHERE C.CODIGO_INTERNO = E.ID_CLIENTE AND
  ESTADO = 'pago' AND E.REGISTO_ENCOMENDA > SYSDATE - 365)                         AS "Number of payed orders(last 12 months)",
  (SELECT count(*) FROM ENCOMENDA E INNER JOIN ENTREGA ET ON E.NUM_ENCOMENDA = ET.NUM_ENCOMENDA
  WHERE C.CODIGO_INTERNO = E.ID_CLIENTE AND ESTADO = 'pendente' AND ET.ESTADO_ENTREGA='entregue')      AS "Number of orders awaiting payment"
FROM CLIENTE C;