CREATE OR REPLACE PROCEDURE UpdateIncidentDate as

    dataUltimoIncidente date;

    CURSOR c_clients IS SELECT CODIGO_INTERNO FROM CLIENTE;

BEGIN
    FOR cur_cliente  IN c_clients
    LOOP
    EXIT WHEN c_clients%NOTFOUND;

    SELECT MAX(I.DATA_OCORRENCIA) into dataUltimoIncidente FROM INCIDENTE I, ENCOMENDA E, CLIENTE C
    WHERE I.NUM_ENCOMENDA=E.NUM_ENCOMENDA AND E.ID_CLIENTE=C.CODIGO_INTERNO AND C.CODIGO_INTERNO=E.ID_CLIENTE AND
    E.NUM_ENCOMENDA=I.NUM_ENCOMENDA AND C.CODIGO_INTERNO=cur_cliente.CODIGO_INTERNO AND I.DATA_OCORRENCIA <= SYSDATE;


    UPDATE CLIENTE SET DATA_ULTIMO_INCIDENTE = dataUltimoIncidente WHERE CODIGO_INTERNO = cur_cliente.CODIGO_INTERNO;
     end LOOP;
end;
