CREATE OR REPLACE VIEW CompararVendas AS
SELECT T1.MES,
       P.NOMEPRODUTO                    as NOME_PRODUTO,
       T1.ANO                   as PRIMEIRO_ANO,
       V1.QUANTIDADE               as VENDAS_PRIMEIRO_ANO,
       T2.ANO                   as SEGUNDO_ANO,
       V2.QUANTIDADE               as VENDAS_SEGUNDO_ANO,
       V1.QUANTIDADE - V2.QUANTIDADE as DIFERENCA
FROM VENDA V1
         JOIN TEMPO T1 on V1.IDTEMPO = T1.IDTEMPO
         JOIN PRODUTO P on P.IDPRODUTO = V1.IDPRODUTO,
     VENDA V2
         JOIN TEMPO T2 on T2.IDTEMPO = V2.IDTEMPO
WHERE T1.MES = T2.MES
  AND V1.IDPRODUTO = V2.IDPRODUTO
  AND V1.IDCLIENTE = V2.IDCLIENTE;



  SELECT MES, NOME_PRODUTO, VENDAS_PRIMEIRO_ANO, DIFERENCA
    FROM CompararVendas
    WHERE PRIMEIRO_ANO = 2020
      AND SEGUNDO_ANO = 2019;